# Auth: Johan Hanekom

# Pro tip: run "tmux source ~/.tmux.conf" to see if syntax is breaking

# ref: https://www.youtube.com/watch?v=WwRljAR9N30

# ================= // TERMINAL COLORS // ================= 

# ref: https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# ================= // REDEFINE LEADER KEYBINDING // ================= 

# Unbind the vanilla leader and set a new one
set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

# ================= // REFRESH CONFIX // ================= 

# Ability to reload the conf using leader-r
unbind r
bind r source-file ~/.tmux.conf

# ================= // SMOOTHER UI EXPERIENCE // ================= 

# Disable the waiting time when pressing escape, for smoother neovim usage
set -s escape-time 0

# Enable mouse so that I can resize using the mouse
set -g mouse on

# Enable extended support for some moe complex terminal emulator features
# Please disable if it causes problems!
set-option -s focus-events on

# ================= // TMUX INDEXING // ================= 

# Make the window numbering start at 1
set -g base-index 1

# Fix Terminal Title display
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

# ================= // PANE MANAGEMENT // ================= 

# alt-arrow pane switching (no prefix needed)
bind -r ^ last-window
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R

# ctrl-alt pane management (no prefix needed)
bind -n C-M-v split-window -h -c "#{pane_current_path}"
bind -n C-M-h split-window -v -c "#{pane_current_path}"
bind -n C-M-x kill-pane

# window management
bind -n C-M-w new-window
bind -n C-M-d kill-window

# ================= // MISC RANDOM THINGS // ================= 

# Some other cool stuff
bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/todo.md"

# ================= // APPEARANCE // ================= 

BG="#444444"
FG="#ececec"

# Posistion
set -g status-position bottom

# Color
set-option -g status-style bg=${BG},fg=${FG}

# Center
set-option -g status-justify centre

# Contents
set-option -g status-left "#S "
set-option -g status-right "%d %B %Y | %A | %H:%M "










